name: shapeblinder
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: any
  touchable: any
  shared_preferences: any

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/tap.svg

    - assets/svg/circle.svg
    - assets/svg/cross.svg
    - assets/svg/donut.svg
    - assets/svg/line.svg
    - assets/svg/oval.svg
    - assets/svg/square.svg

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf
        - asset: assets/fonts/Muli-Italic.ttf
          style: italic

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
